apiVersion: v1
kind: Service
metadata:
  name: test-approval
  namespace: test-approval
  labels:
    app: test-approval
    app.kubernetes.io/name: test-approval
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  selector:
    app: test-approval
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
